routes/web.php
<?php

use App\Http\Controllers\Auth\ConfirmPasswordController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/","WebController@index");
Route::get("como-jugar","WebController@comoJugar")->name("jugar");

//REGISTRO
Route::get("registrar","RegistrarController@registrarse")->name("registrarse");
Route::post("registrar","RegistrarController@store");
Route::get("activar/{username}","RegistrarController@activar")->name("activar");

//SOLICITUDES
Route::get("solicitar/usuario","SolicitarController@solicitarUsuario")->name("solicitar.usuario");
Route::post("solicitar/usuario","SolicitarController@procesarSolicitarUsuario");
Route::get("solicitar/cambio-clave","SolicitarController@solicitarCambioClave")->name("solicitar.cambio.clave");
Route::post("solicitar/cambio-clave","SolicitarController@procesarSolicitarCambioClave");
Route::get("cambiar-clave/{token}","CambioClaveController@cambiarClave")->name("cambiar.clave");
Route::post("cambiar-clave/{token}","CambioClaveController@procesarCambiarClave");

//INTRANET - CUENTA
Auth::routes(['register'=>false]);
Route::get('/home', 'HomeController@index')->name('home');
Route::prefix('cuenta')->name("cuenta.")->group(function () {
    Route::namespace('Cuenta')->middleware('auth')->group(function(){
        Route::get('mi-cuenta', 'CuentaController@index')->name('cuenta');
//        Route::get('mis-datos', 'InfoController@index')->name('info');
        Route::get('mis-personajes', 'PersonajesController@index')->name('personajes');
    });

});


//INTRANET - ADMINISTRACION
Route::prefix('intranet')->name("intranet.")->group(function () {

    Route::get('login', [LoginController::class, 'showAdminLoginForm'])->name('login');
    Route::post('login', [LoginController::class,'adminLogin']);
    Route::get('register', [RegisterController::class,'showAdminRegisterForm']);
    Route::post('register', [RegisterController::class,'createAdmin']);
    Route::get('password/confirm', [ConfirmPasswordController::class, 'showConfirmForm']);
    Route::post('password/confirm', [ConfirmPasswordController::class, 'confirm']);

    Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm']);
    Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail']);
    Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm']);
    Route::post('password/reset', [ResetPasswordController::class, 'reset']);
//
    Route::namespace('Intranet')->middleware('auth:admin')->group(function(){
        Route::post('logout', [LoginController::class,'logout'])->name("logout");
        Route::get('/', [\App\Http\Controllers\Intranet\HomeController::class,'index'])->name('home');
        Route::get('cuentas', 'CuentasController@index')->name('cuentas');
        Route::get('cuenta/{username}/personajes', 'CuentasController@personajes')->name('cuentas.personajes');
        Route::get('cuenta/{username}/activar', 'CuentasController@activar')->name('cuentas.activar');
        Route::get('cuenta/{username}/editar', 'CuentasController@editar')->name('cuentas.editar');
        Route::put('cuenta/{username}/editar', 'CuentasController@update');

        Route::get('personajes', 'PersonajesController@index')->name('personajes');

        Route::get('items', 'ItemsController@index')->name('items');


        Route::get('correo/enviar', 'CorreoController@formulario')->name('correo');
        Route::post('correo/enviar', 'CorreoController@enviar')->name('correo');
        Route::get('correo/agregar-adjunto/{ID}', 'CorreoController@agregar')->name('correo.agregar');
        Route::get('correo/remover-adjunto/{ID}', 'CorreoController@remover')->name('correo.remover');
    });
});

app/Http/Controllers/Intranet/CorreoController.php
<?php

namespace App\Http\Controllers\Intranet;

use App\Http\Controllers\Controller;
use App\ItemTemplate;
use App\Servidor;
use Illuminate\Http\Request;

class CorreoController extends Controller
{
    //
    public function formulario(Request $request){
        $id_adjuntos=$request->session()->get('adjuntos');
        $adjuntos=ItemTemplate::buscarPorIds($id_adjuntos)->get();


        $data=compact('adjuntos');
        return view('intranet.correo',$data);
    }

    public function enviar(Request $request){
        $usuario=$request->input('username');
        $asunto=$request->input('asunto');
        $mensaje=$request->input('mensaje');
        $adjuntos=$request->input('adjuntos',[]);

        $items_adjuntos="";
        foreach($adjuntos as $item=>$cantidad){
            $items_adjuntos.=$item.":".$cantidad." ";
        }

        //.send items $charactername "asunto" "Gracias por esforzarte, has alcanzado el maximo nivel" 44413:1
        $comando='.send items '.$usuario.' "'.$asunto.'" "'.$mensaje.'" '.trim($items_adjuntos);


        Servidor::comando($comando);

        $request->session()->forget('adjuntos');

        return redirect()->back();
    }

    public function agregar(Request $request, $id){
        $request->session()->push('adjuntos', $id);

        return redirect()->back();
    }

    public function remover(Request $request, $id){
        $session=collect($request->session()->get('adjuntos'));

        $key =  $session->search($id);

        $request->session()->forget('adjuntos.'.$key);
        return redirect()->back();
    }
}

app/Http/Controllers/Intranet/CuentasController.php
<?php

namespace App\Http\Controllers\Intranet;

use App\Cuenta;
use App\Http\Controllers\Controller;
use App\Personaje;
use Illuminate\Http\Request;

class CuentasController extends Controller
{
    //
    public function index(Request  $request){
        $filtro=$request->get('filtro');

        $cuentas=Cuenta::filtrar($filtro)->paginate(10)->appends(compact('filtro'));

        foreach($cuentas as $cuenta){
            $cuenta->url_personajes=route('intranet.cuentas.personajes',[$cuenta->username]);
            $cuenta->url_activar=route('intranet.cuentas.activar',[$cuenta->username]);
            $cuenta->url_editar=route('intranet.cuentas.editar',[$cuenta->username]);
        }

        $data=compact('cuentas','filtro');
        return view('intranet.cuentas',$data);
    }

    public function personajes(Request $request, $username){

        $cuenta=Cuenta::where('username',$username)->first();

        if($cuenta instanceof Cuenta){
            $personajes=Personaje::where('account',$cuenta->id)->paginate(10);

            foreach($personajes as $personaje){

            }

            $data=compact('cuenta','personajes');
        }

        return view('intranet.cuentas-personajes',$data);
    }

    public function activar($username){
        $cuenta=Cuenta::where('username',$username)->first();

        if($cuenta instanceof Cuenta){
            $cuenta->locked=0;
            $cuenta->save();

            $status_tipo=true;
            $status_mensaje='La cuenta se actualizó con éxito.';
        }

        return redirect()->back()->with([
            'status_tipo'=>$status_tipo,
            'status_mensaje'=>$status_mensaje
        ]);
    }

    public function editar($username){
        $cuenta=Cuenta::where('username',$username)->first();
        if(!($cuenta instanceof Cuenta)){
            abort(404,"No encontrado");
        }

        $data=compact('cuenta');
        return view('intranet.cuenta-editar',$data);
    }

    public function update(Request $request, $username){
        $this->validate($request,[
           'username'=>'required',
           'email'=>'required'
        ]);

        $cuenta=Cuenta::where('username',$username)->first();
        if($cuenta instanceof Cuenta){
            $cuenta->username=strtoupper($request->input('username'));
            $cuenta->email=$request->input('email');
            $cuenta->save();

            $status_tipo=true;
            $status_mensaje='La cuenta se actualizó con éxito.';

        }else{
            $status_tipo=false;
            $status_mensaje='La cuenta no se pudo actualizar.';

        }
        return redirect()->back()->with([
            'status_tipo'=>$status_tipo,
            'status_mensaje'=>$status_mensaje
        ]);
    }
}

app/Http/Controllers/Intranet/HomeController.php
<?php

namespace App\Http\Controllers\Intranet;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/Intranet/ItemsController.php
<?php

namespace App\Http\Controllers\Intranet;

use App\Http\Controllers\Controller;
use App\ItemTemplate;
use Illuminate\Http\Request;

class ItemsController extends Controller
{
    //

    public function index(Request $request){
        $filtro=$request->get('filtro');
        $items=ItemTemplate::filtrar($filtro)->paginate(10)->appends(compact('filtro'));



        $data=compact('items','filtro');
        return view('intranet.items',$data);
    }
}

app/Http/Controllers/Intranet/PersonajesController.php
<?php

namespace App\Http\Controllers\Intranet;

use App\Cuenta;
use App\Http\Controllers\Controller;
use App\Personaje;
use Illuminate\Http\Request;

class PersonajesController extends Controller
{
    //
    public function index(Request  $request){
        $filtro=$request->get('filtro');
        $personajes=Personaje::filtrar($filtro)->paginate(10)->appends(compact('filtro'));

        foreach($personajes as $personaje){

        }

        $data=compact('personajes','filtro');
        return view('intranet.personajes',$data);
    }
}

resources/views/intranet/correo.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-6 mt-2 offset-3">
                <div class="card bg-dark text-white" >
                    <div class="card-body">
                        <h5 class="card-title text-center">Enviar regalos por correo</h5>
                        @if(session()->exists("status_mensaje"))
                            @if(session()->get("status_tipo")===true)
                                <div class="alert alert-success">{{ session()->get("status_mensaje") }}</div>
                            @elseif(session()->get("status_tipo")===false)
                                <div class="alert alert-danger">{{ session()->get("status_mensaje") }}</div>
                            @endif
                        @endif
                        <form class="form-horizontal" method="POST" action="">
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="inputUsuario">Usuario</label>
                                <input type="text" name="username" id="inputUsuario" aria-describedby="usuario"
                                       class="form-control @error('username') is-invalid @enderror" value="{{ old('username') }}">
                                {{--                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>--}}
                                @error('username')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="inputAsunto">Asunto</label>
                                <input type="text" name="asunto" id="inputAsunto" aria-describedby="asunto"
                                       class="form-control @error('asunto') is-invalid @enderror" value="{{ old('asunto','Regalo por tu logro') }}">
                                {{--                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>--}}
                                @error('asunto')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="inputMensaje">Mensaje</label>

                                {{--                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>--}}
                                <textarea name="mensaje" id="inputMensaje" class="form-control @error('mensaje') is-invalid @enderror" aria-describedby="usuario">{{ old('mensaje','Por tu esfuerzo en el juego has ganado las siguientes recompensas, felicitaciones') }}</textarea>
                                @error('mensaje')
                                <div class="alert alert-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            @if(isset($adjuntos) && $adjuntos->count()>0)
                                <div class="form-group">
                                    <label for="inputMensaje">Adjuntos</label>
                                    <table class="table table-bordered table-sm">
                                        <tr>
                                            <th class="bg-white">Item</th>
                                            <th class="bg-white">Cantidad</th>
                                        </tr>
                                        @foreach($adjuntos as $item)
                                            <tr>
                                                <td class="text-white">{{ $item->nombre }}</td>
                                                <td>
                                                    <input type="text" name="adjuntos[{{ $item->entry }}]" value="1" class="form-control-sm">
                                                    <a href="{{ route('intranet.correo.remover',$item->entry) }}" class="btn btn-danger btn-sm">Remover</a>
                                                </td>
                                            </tr>
                                            @endforeach
                                    </table>

                                </div>
                            @endif

                            <button type="submit" class="btn btn-primary float-right">
                                Enviar
                            </button>
                        </form>
                        {{--                <a href="#" class="btn btn-primary">Go somewhere</a>--}}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/intranet/cuenta-editar.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-3">
            <div class="card bg-dark text-white" >
                <div class="card-body">
                    <h5 class="card-title text-center">Editar</h5>
                    @if(session()->exists("status_mensaje"))
                        @if(session()->get("status_tipo")===true)
                            <div class="alert alert-success">{{ session()->get("status_mensaje") }}</div>
                        @elseif(session()->get("status_tipo")===false)
                            <div class="alert alert-danger">{{ session()->get("status_mensaje") }}</div>
                        @endif
                    @endif
                    <form class="form-horizontal" method="POST" action="">
                        {{ csrf_field() }}
                        {{ method_field('put') }}
                        <div class="form-group">
                            <label for="inputUsuario">Usuario</label>
                            <input type="text" name="username" id="inputUsuario" aria-describedby="usuario"
                                   class="form-control @error('username') is-invalid @enderror" value="{{ old('username',$cuenta->username) }}">
    {{--                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>--}}
                            @error('username')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="inputEmail">Email</label>
                            <input type="text" name="email" id="inputEmail" aria-describedby="email"
                                   class="form-control @error('email') is-invalid @enderror" value="{{ old('email',$cuenta->email) }}">
                            {{--                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>--}}
                            @error('email')
                            <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>

                        <button type="submit" class="btn btn-primary float-right">
                            Actualizar cuenta
                        </button>
                    </form>
    {{--                <a href="#" class="btn btn-primary">Go somewhere</a>--}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/intranet/cuentas-personajes.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card bg-dark">
                    <div class="card-header">
                        <h4 class="card-title mb-0">Personajes de {{ $cuenta->username }}</h4>
                    </div>
                    <div class="card-body text-white">
                        <table class="table table-bordered table-dark table-sm mb-0">
                            <thead>
                            <tr>
                                <th class="text-center">Nro</th>
                                <th colspan="3" class="text-center">Personajes</th>
                                <th class="text-center">Victorias</th>
                                <th class="text-center">Oro</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($personajes as $posicion=>$personaje)
                                <tr class="{{ $personaje->getBando()==\App\Personaje::ALIANZA?'alianza':'horda' }}">
                                    <td class="text-center">{{ $posicion+1+$personajes->perPage()*($personajes->currentPage()-1) }}</td>
                                    <td class="text-center">{{ $personaje->name  }}</td>
                                    <td class="text-center">{{ $personaje->level }}</td>
                                    <td class="text-center">
                                        <img src="{{ $personaje->getImagenBando() }}" alt="">
                                        <img src="{{ $personaje->getImagenClase() }}" alt="">
                                        <img src="{{ $personaje->getImagenRaza() }}" alt="">
                                    </td>
                                    <td class="text-right">{{ $personaje->totalKills }}</td>
                                    <td class="text-right">
                                        {{ $personaje->getOro() }} <i class="fas fa-coins text-warning"></i>
                                        {{ $personaje->getPlata() }} <i class="fas fa-coins"></i>
                                        {{ $personaje->getBronce() }} <i class="fas fa-coins text-danger"></i>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="5">No hay personajes disponibles</td>
                                </tr>
                            @endforelse
                            </tbody>
                            <tfoot>
                            @if($personajes->hasPages())
                                <tr>
                                    <td class="text-center" colspan="5">{{ $personajes->links('vendor.pagination.simple-minimo') }}</td>
                                </tr>
                            @endif
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/intranet/cuentas.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card bg-dark">
                    <div class="card-header">
                        <form class="form-inline my-lg-0 ">
                            <h4 class="card-title col-md-6 mb-0">Cuentas registradas</h4>
                            <div class="col-md-6 ">
                                <input name="filtro" class="form-control mr-sm-2"
                                       type="search" placeholder="Ingrese un filtro" aria-label="Search"
                                       value="{{ $filtro }}"
                                >
                                <button class="btn btn-success my-2 my-sm-0" type="submit">
                                    <i class="fas fa-search"></i> Filtrar
                                </button>
                            </div>
                        </form>
                    </div>
                    <div class="card-body text-white">
                        <table class="table table-hover table-bordered table-dark table-sm mb-0">
                            <thead>
                            <tr>
                                <th class="text-center">Nro</th>
                                <th class="text-center">Cuenta / Email</th>
                                <th class="text-center">Ultima conexión</th>
                                <th class="text-center">Registro</th>
                                <th class="text-center">Conexion</th>
                                <th class="text-center">Bloqueado</th>
                                <th class="text-center">Opciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($cuentas as $posicion=>$cuenta)
                                <tr >
                                    <td class="text-center">{{ $posicion+1+$cuentas->perPage()*($cuentas->currentPage()-1) }}</td>
                                    <td class="text-center">{{ $cuenta->username  }}<br>{{ $cuenta->email }}</td>
                                    <td class="text-center">
                                        {{ $cuenta->last_login }} <br>
                                        {{ $cuenta->desconectadoDesde() }}
                                    </td>
                                    <td class="text-center">
                                        {{ $cuenta->joindate }}
                                        <br>
                                        {{ $cuenta->registradoDesde() }}
                                    </td>
                                    <td class="text-center">
                                        @if($cuenta->online==1)
                                            <a class="btn btn-success btn-sm col-12 ">
                                                <i class="fas fa-thumbs-up "></i> Conectado
                                            </a>
                                        @else
                                            <a class="btn btn-danger btn-sm col-12">
                                                <i class="fas fa-thumbs-down "></i> Desconectado
                                            </a>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        @if($cuenta->locked==0)
                                            <a class="btn btn-success btn-sm col-12">
                                                <i class="fas fa-check "></i> Activada
                                            </a>
                                        @else
                                            <a href="{{ $cuenta->url_activar }}" class="btn btn-danger btn-sm col-12">
                                                <i class="fas fa-ban"></i> Por confirmar
                                            </a>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        <a href="{{ $cuenta->url_editar }}" class="btn btn-primary btn-sm">Editar cuenta</a>
                                        <a href="{{ $cuenta->url_personajes }}" class="btn btn-primary btn-sm">
                                            Ver personajes
                                        </a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="9">No hay cuentas disponibles</td>
                                </tr>
                            @endforelse
                            </tbody>
                            <tfoot>
                            @if($cuentas->hasPages())
                                <tr>
                                    <td class="text-center" colspan="9">{{ $cuentas->links() }}</td>
                                </tr>
                            @endif
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/intranet/items.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 mt-2 offset-md-2">
                <div class="card bg-dark">
                    <div class="card-header">
                        <h4 class="card-title mb-0">Items del Juego</h4>
                    </div>
                    <div class="card-body text-white">
                        <form action="" class="form ">
                            <input type="text" name="filtro" value="{{old('filtro',$filtro)}}" class="form-control">
                        </form>
                        <table class="table table-bordered table-dark table-sm mb-0">
                            <thead>
                            <tr>
                                <th class="text-center">Entry</th>
                                <th colspan="3" class="text-center">Nombre</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($items as $posicion=>$item)
                                <tr >
                                    <td class="text-center">{{ $item->entry  }}</td>
                                    <td class="text-center">{{ $item->nombre }}</td>
                                    <td class="text-center" >
                                        <a href="{{ route('intranet.correo.agregar',$item->entry) }}" class="btn btn-outline-success btn-sm">Agregar</a>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="5">No hay items disponibles</td>
                                </tr>
                            @endforelse
                            </tbody>
                            <tfoot>
                            @if($items->hasPages())
                                <tr>
                                    <td class="text-center" colspan="5">{{ $items->links('vendor.pagination.simple-minimo') }}</td>
                                </tr>
                            @endif
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection