routes/web.php
<?php

use App\Http\Controllers\Auth\ConfirmPasswordController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ResetPasswordController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/","WebController@index");
Route::get("como-jugar","WebController@comoJugar")->name("jugar");

//REGISTRO
Route::get("registrar","RegistrarController@registrarse")->name("registrarse");
Route::post("registrar","RegistrarController@store");
Route::get("activar/{username}","RegistrarController@activar")->name("activar");

//SOLICITUDES
Route::get("solicitar/usuario","SolicitarController@solicitarUsuario")->name("solicitar.usuario");
Route::post("solicitar/usuario","SolicitarController@procesarSolicitarUsuario");
Route::get("solicitar/cambio-clave","SolicitarController@solicitarCambioClave")->name("solicitar.cambio.clave");
Route::post("solicitar/cambio-clave","SolicitarController@procesarSolicitarCambioClave");
Route::get("cambiar-clave/{token}","CambioClaveController@cambiarClave")->name("cambiar.clave");
Route::post("cambiar-clave/{token}","CambioClaveController@procesarCambiarClave");

//INTRANET - CUENTA
Auth::routes(['register'=>false]);
Route::get('/home', 'HomeController@index')->name('home');
Route::prefix('cuenta')->name("cuenta.")->group(function () {
    Route::namespace('Cuenta')->middleware('auth')->group(function(){
        Route::get('mi-cuenta', 'CuentaController@index')->name('cuenta');
//        Route::get('mis-datos', 'InfoController@index')->name('info');
        Route::get('mis-personajes', 'PersonajesController@index')->name('personajes');
    });

});


//INTRANET - ADMINISTRACION
Route::prefix('intranet')->name("intranet.")->group(function () {

    Route::get('login', [LoginController::class, 'showAdminLoginForm'])->name('login');
    Route::post('login', [LoginController::class,'adminLogin']);
    Route::get('register', [RegisterController::class,'showAdminRegisterForm']);
    Route::post('register', [RegisterController::class,'createAdmin']);
    Route::get('password/confirm', [ConfirmPasswordController::class, 'showConfirmForm']);
    Route::post('password/confirm', [ConfirmPasswordController::class, 'confirm']);

    Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm']);
    Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail']);
    Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm']);
    Route::post('password/reset', [ResetPasswordController::class, 'reset']);
//
    Route::namespace('Intranet')->middleware('auth:admin')->group(function(){
        Route::post('logout', [LoginController::class,'logout'])->name("logout");
        Route::get('/', [\App\Http\Controllers\Intranet\HomeController::class,'index'])->name('home');
        Route::get('cuentas', 'CuentasController@index')->name('cuentas');
        Route::get('cuenta/{username}/personajes', 'CuentasController@personajes')->name('cuentas.personajes');
        Route::get('cuenta/{username}/activar', 'CuentasController@activar')->name('cuentas.activar');
        Route::get('cuenta/{username}/editar', 'CuentasController@editar')->name('cuentas.editar');
        Route::put('cuenta/{username}/editar', 'CuentasController@update');

        Route::get('personajes', 'PersonajesController@index')->name('personajes');

        Route::get('items', 'ItemsController@index')->name('items');


        Route::get('correo/enviar', 'CorreoController@formulario')->name('correo');
        Route::post('correo/enviar', 'CorreoController@enviar')->name('correo');
        Route::get('correo/agregar-adjunto/{ID}', 'CorreoController@agregar')->name('correo.agregar');
        Route::get('correo/remover-adjunto/{ID}', 'CorreoController@remover')->name('correo.remover');
    });
});

resources/views/layouts/analytics.blade.php
<!-- Global site tag (gtag.js) - Google Analytics -->
{{--    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-128951021-1"></script>--}}
@if(!env("APP_DEBUG"))
    {{--        <script>--}}
    {{--            window.dataLayer = window.dataLayer || [];--}}
    {{--            function gtag(){dataLayer.push(arguments);}--}}
    {{--            gtag('js', new Date());--}}

    {{--            gtag('config', 'UA-128951021-1');--}}
    {{--        </script>--}}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-VEXVVBB4NN"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-VEXVVBB4NN');
    </script>
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
    @include('layouts.analytics')
</head>
<body class="">
    <div id="app">
        <div class="text-center my-2 mt-2">
            <img src="{{ asset("img/logo.png") }}" class="img-fluid rounded" alt="...">
        </div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
           <div class="container ">
               <!-- Navbar content -->
               <a class="navbar-brand" href="#"></a>
               <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                   <span class="navbar-toggler-icon"></span>
               </button>

               <div class="collapse navbar-collapse" id="navbarToggle">
                   @auth('admin')
                       @include('layouts.menu-admin')
                   @elseauth()
                       @include('layouts.menu-cuenta')
                   @else
                       <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                           <li class="nav-item ">
                               <a class="nav-link" href="/">Inicio <span class="sr-only">(current)</span></a>
                           </li>
                           <li class="nav-item">
                               <a class="nav-link" href="{{ route('registrarse') }}">Registrarse</a>
                           </li>
                           <li class="nav-item dropdown">
                               <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                   Solicitar accesos
                               </a>
                               <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                   <a class="dropdown-item" href="{{ route('solicitar.usuario') }}">Olvidé mi usuario</a>
                                   <a class="dropdown-item" href="{{ route('solicitar.cambio.clave') }}">Olvidé mi clave</a>
                               </div>
                           </li>
                           <li class="nav-item">
                               <a class="nav-link " href="{{ route('jugar') }}" >Como jugar</a>
                           </li>


                       </ul>

                       <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                           <li class="nav-item ">
                               <a class="nav-link" href="{{ route('login')}}">Iniciar sesión<span class="sr-only">(current)</span></a>
                           </li>
                       </ul>
                   @endauth
               </div>
           </div>
        </nav>
        <div class="container">
            @yield('content')
            <div class="text-center my-2">
                wowgblocal 2020
            </div>
        </div>
    </div>

    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}"></script>


</body>
</html>

resources/views/layouts/menu-admin.blade.php
<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    <li class="nav-item ">
        <a class="nav-link" href="/home">Inicio <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item ">
        <a class="nav-link" href="{{ route('intranet.cuentas')}}">Todas las cuentas <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item ">
        <a class="nav-link" href="{{ route('intranet.personajes')}}">Todos los personajes <span class="sr-only">(current)</span></a>
    </li>

    <li class="nav-item ">
        <a class="nav-link" href="{{ route('intranet.items')}}">Buscar items <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item ">
        <a class="nav-link" href="{{ route('intranet.correo')}}">Enviar regalos<span class="sr-only">(current)</span></a>
    </li>
</ul>

<ul class="navbar-nav ml-auto mt-2 mt-lg-0">
    <li class="nav-item ">
        <a class="nav-link" href="/">Web <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item dropdown">
        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
            {{ Auth::user()->name }}
        </a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ route('logout') }}"
               onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                {{ __('Logout') }}
            </a>

            <form id="logout-form" action="{{ route('intranet.logout') }}" method="POST" class="d-none">
                @csrf
            </form>
        </div>
    </li>
</ul>

resources/views/layouts/menu-cuenta.blade.php
<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    <li class="nav-item ">
        <a class="nav-link" href="/home">Inicio <span class="sr-only">(current)</span></a>
    </li>
{{--    <li class="nav-item ">--}}
{{--        <a class="nav-link" href="{{ route('cuenta.info')}}">Mi información <span class="sr-only">(current)</span></a>--}}
{{--    </li>--}}
    <li class="nav-item ">
        <a class="nav-link" href="{{ route('cuenta.cuenta')}}">Mi cuenta <span class="sr-only">(current)</span></a>
    </li>
   <li class="nav-item ">
       <a class="nav-link" href="{{ route('cuenta.personajes')}}">Mis personajes <span class="sr-only">(current)</span></a>
   </li>
</ul>

<ul class="navbar-nav ml-auto mt-2 mt-lg-0">
    <li class="nav-item ">
        <a class="nav-link" href="/">Web <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item dropdown">
        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
            {{ Auth::user()->username }}
        </a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ route('logout') }}"
               onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                {{ __('Logout') }}
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>
        </div>
    </li>
</ul>

resources/views/layouts/metadata-property.blade.php
<!-- MS, fb & Whatsapp -->

<!-- MS Tile - for Microsoft apps-->
{{--<meta name="msapplication-TileImage" content="http://www.example.com/image01.jpg">--}}

<!-- fb & Whatsapp -->

<!-- Site Name, Title, and Description to be displayed -->
{{--<meta property="og:site_name" content="">--}}
<meta property="og:title" content="{{ env('APP_NAME') }}">
<meta property="og:description" content="Servidor wowgblocal v3.3.5a, Registrate y juega.">

<!-- Image to display -->
<!-- Replace   «example.com/image01.jpg» with your own -->
<meta property="og:image" content="{{ asset("img/logo.png") }}">

<!-- No need to change anything here -->
<meta property="og:type" content="website" />
<meta property="og:image:type" content="image/png">

<!-- Size of image. Any size up to 300. Anything above 300px will not work in WhatsApp -->
<meta property="og:image:width" content="300">
<meta property="og:image:height" content="300">

<!-- Website to visit when clicked in fb or WhatsApp-->
<meta property="og:url" content="{{ env('APP_URL') }}">